### ISSUE TITLE
How does it work in background?

### ISSUE THREAD

**Issue by fabianmendes** [Itai-Nelken/Nativefier-Whatsapp-Web#1]
I mean, I don't want to it keeps running background consuming CPU, I would like to kill it when desired (saw on the Pi-Apps). I'm just asking, thanks

**Comment by Itai-Nelken** [comment]
it has a tray icon (in the taskbar), depending on your OS left/right click it and click on 'quit'.

I won't ever make a app that you can't stop in a simple way.

**Comment by Itai-Nelken** [comment]
@fabianmendes does that answer your question?

**Comment by fabianmendes** [comment]
Yes,thaaanks

**Comment by fabianmendes** [comment]
@Itai-Nelken hey, excuse me. Hello again.
I want to recreate this for _jupyter notebook_, but I don't know how did you make an Icon Tray for task-bar notification. Also, I've just realized that my WhatappWeb doesn't show on the notifications once I close its windows (downloaded and updated from Pi-apps of course).
I have this, but I'm very interesting to make it work underground and click on its icon from the notifications task-bar, but I absolutely don't know.
I got this forked from your install file script from Pi-apps:
```
#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd $HOME
mkdir -p ~/JupyterNotebook/userdata

echo "#!/bin/bash
chromium-browser %U --user-agent='Mozilla/5.0 (X11; CrOS armv7l 11895.95.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.125 Safari/537.36' --user-data-dir=$HOME/JupyterNotebook/userdata --app=http://localhost:8888/tree  --window-size=1200,700" > ~/JupyterNotebook/jupyter_notebook.sh
sudo chmod +x ~/JupyterNotebook/jupyter_notebook.sh

echo "[Desktop Entry]
Name=Jupyter Notebook
Comment=Jupyter Notebook webapp.
Exec=$HOME/JupyterNotebook/jupyter_notebook.sh
Path=$HOME/JupyterNotebook
Icon=$(dirname "$0")/icon-64.png
Terminal=false
StartupNotify=true
Type=Application
Categories=Programming;" > ~/.local/share/applications/jupyter_notebook.desktop || error "Failed to create menu button!"
```
Script also @ [install.txt](https://github.com/Itai-Nelken/Nativefier-WebApps/files/5984600/install.txt)
I want to create one similar app for Jupyter (notebook) as you've made for Whatsapp, that inspired me. I need it, I would like to close and open my Jupyter every time I want without the annoying terminal always open and having its own window for Jupyter N. Only. And better than that, to close it from the Icon tray on the notifications with the _close_ option, you know!

Please,
Fabian M. :)

PS: Otherwise, I would like to include it to Pi-apps (It would be as it is, a button.. but also a Jupyter installation with just one click. I would do that right later)

EDIT: or from Botspot, I don't know haha <- https://github.com/Botspot/pi-apps/blob/master/apps/Whatsapp/install

**Comment by Itai-Nelken** [comment]
>Also, I've just realized that my WhatappWeb doesn't show on the notifications once I close its windows (downloaded and updated from Pi-apps of course).

the WhatsappWeb app currently in pi-apps has no tray icon because of a bug with [nativefier](https://github.com/jiahaog/nativefier) that was used for it: https://github.com/nativefier/nativefier/issues/1112

you can try to use nativefier for a tray icon, but I don't think it works with local links:
1) install it: 
    * install node.js from pi-apps
    * run `sudo npm install -g nativefier`
2) run the following command, but change the link and arch to whatever you need:
`nativefier --arch=armv7l --tray web.whatsapp.com`
read [this](https://github.com/nativefier/nativefier/blob/master/docs/api.md) for more info about all of nativefier's abilities.

**Comment by Itai-Nelken** [comment]
btw @fabianmendes the nativefier whatsapp web works again. so once botspot re-adds it to pi-apps, you can use the tray again.

**Comment by fabianmendes** [comment]
Do you think I could do that similar with Jupyter Notebook? I want to
recreate it for it

**Comment by Itai-Nelken** [comment]
>Do you think I could do that similar with Jupyter Notebook? I want to
recreate it for it

you can try:
1) install nativefier
    * install node.js from pi-apps
    * run `sudo npm install -g nativefier`
2) run 
```bash
ARCH="`uname -m`"
nativefier --arch=$ARCH --tray http://localhost:8888/tree
```

**Comment by fabianmendes** [comment]
All right all righr, thanks I will try it out!
